package com.afrasilv.spotifyclientapp.model;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBTokenDaoConfig;

    private final DBTokenDao dBTokenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBTokenDaoConfig = daoConfigMap.get(DBTokenDao.class).clone();
        dBTokenDaoConfig.initIdentityScope(type);

        dBTokenDao = new DBTokenDao(dBTokenDaoConfig, this);

        registerDao(DBToken.class, dBTokenDao);
    }
    
    public void clear() {
        dBTokenDaoConfig.getIdentityScope().clear();
    }

    public DBTokenDao getDBTokenDao() {
        return dBTokenDao;
    }

}
